export const CART_ACTION_TYPE = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUNATITY: "DECREASE_QUANTITY",
} as const;
